### ISSUE TITLE
Make: missing Dependencies: hdf5 and slow5lib

### ISSUE THREAD

**Issue by Cuypers-Wim** [CMU-SAFARI/RawAlign#1]
Thank you for your efforts on this project, looks really cool! I'm genuinely interested in utilizing RawAlign for my microbial genomics & nanopore work. However, while attempting to set it up, I encountered a few challenges that I hope can be addressed.

## Description
While attempting to build RawAlign from source, I encountered errors indicating that the `hdf5` and `slow5lib` dependencies are missing from the `extern` directory. 

## What I did
1. I cloned the RawAlign repository.
2. Navigated to the RawAlign directory and ran `make`.

## Actual Behavior
The build process fails with errors indicating that it cannot find the `hdf5` and `slow5lib` directories within the `extern` directory. Here are some relevant snippets of the error messages:

```jsx
/bin/sh: 1: cd: can't cd to ../extern/hdf5
/bin/sh: 3: ./configure: not found
...
make[3]: *** /mnt/[drive]/[project_name]/[subproject]/[tool_name]/RawAlign/src/../extern/slow5lib/: No such file or directory. Stop.
```

## Possible Solution
It seems that the required submodules or external dependencies for `hdf5` and `slow5lib` are not included in the repository. Including instructions on how to obtain these dependencies or adding them as submodules might help resolve the issue.

Thank you for looking into this issue. I'm looking forward to a solution!

**Comment by joellindegger** [comment]
Hi Wim

Thanks for reporting this issue. These dependencies were supposed to be available as submodules and were missing in the prior commit. [ee59c4e](https://github.com/CMU-SAFARI/RawAlign/commit/ee59c4e5d04d8464e134fe5c0c9e1cd38ccc9cc3) Should address the problem.

To use these changes in your cloned repository, please run `git pull` and `git submodule update --init`.

Best,
Joel

**Comment by Cuypers-Wim** [comment]
Seems to work, thank you!
